import { createClient, type SupabaseClient } from '@supabase/supabase-js';

type Template = { id: string; name: string; description: string; document_type: string; version: number; storage_path: string | null; codex_instructions: string };
type ClientRecord = { id: string; company_name: string };
type ClientDocument = { id: string; title: string; status: string; version: number; source_filename: string | null; storage_path: string | null; updated_at: string; client_id: string | null };
const fallbackTemplate: Template = { id: 'local-website-proposal', name: 'Website proposal', description: 'Formal CNVRT proposal with scope, delivery, investment and agreement.', document_type: 'proposal', version: 1, storage_path: null, codex_instructions: 'Use the attached CNVRT website proposal template as the structural and visual source. Replace every bracketed field using the selected client CRM record, approved discovery answers and agreed commercial terms. Preserve the logo, typography, spacing, page furniture and agreement section. Do not invent factual claims, credentials, pricing, dates or deliverables. Flag missing information clearly. Return an editable DOCX and a visually verified PDF.' };
const el = <T extends Element>(root: ParentNode, selector: string) => root.querySelector<T>(selector);
const safe = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char));

export const initialiseDocumentsAdmin = () => {
  const root = document.querySelector<HTMLElement>('[data-documents-admin]'); if (!root) return;
  const auth = el<HTMLElement>(root, '[data-auth-view]'); const workspace = el<HTMLElement>(root, '[data-workspace]');
  const form = el<HTMLFormElement>(root, '[data-login-form]'); const status = el<HTMLElement>(root, '[data-login-status]');
  const docForm = el<HTMLFormElement>(root, '[data-document-form]'); const docStatus = el<HTMLElement>(root, '[data-document-status]');
  const templateSelect = el<HTMLSelectElement>(root, '[data-template-select]'); const clientSelect = el<HTMLSelectElement>(root, '[data-client-select]');
  const url = import.meta.env.PUBLIC_SUPABASE_URL?.trim(); const key = import.meta.env.PUBLIC_SUPABASE_ANON_KEY?.trim();
  let db: SupabaseClient | null = null; let templates: Template[] = []; let clients: ClientRecord[] = []; let documents: ClientDocument[] = [];
  const showWorkspace = () => { if (auth) auth.hidden = true; if (workspace) workspace.hidden = false; };
  const showAuth = () => { if (auth) auth.hidden = false; if (workspace) workspace.hidden = true; };
  const nameFor = (id: string | null) => clients.find((item) => item.id === id)?.company_name || 'Unassigned client';
  const selectedTemplate = () => templates.find((item) => item.id === templateSelect?.value) || templates[0] || fallbackTemplate;
  const generationBrief = () => { const clientName = clients.find((item) => item.id === clientSelect?.value)?.company_name || '[CLIENT NAME]'; return `Create a new CNVRT ${selectedTemplate().name} for ${clientName}.\n\n${selectedTemplate().codex_instructions}\n\nUse the client CRM record and any attached discovery/audit material. Before finalising, confirm the scope, fee, payment schedule, dates and named approver. Save the client DOCX and PDF, then upload the finished file to the CNVRT Documents area.`; };
  const render = () => {
    const templateList = el<HTMLElement>(root, '[data-template-list]');
    if (templateList) templateList.innerHTML = templates.map((item) => `<article class="document-card"><div class="document-card__top"><div><h3>${safe(item.name)}</h3><p>${safe(item.description)}</p></div><i>v${item.version}</i></div><div class="document-card__actions"><button class="admin-button" type="button" data-template-brief="${safe(item.id)}">Copy Codex brief</button>${item.storage_path ? `<button class="admin-button" type="button" data-template-download="${safe(item.id)}">Download template</button>` : ''}</div></article>`).join('');
    if (templateSelect) templateSelect.innerHTML = templates.map((item) => `<option value="${safe(item.id)}">${safe(item.name)} · v${item.version}</option>`).join('');
    if (clientSelect) clientSelect.innerHTML = `<option value="">Choose client</option>${clients.map((item) => `<option value="${safe(item.id)}">${safe(item.company_name)}</option>`).join('')}`;
    const list = el<HTMLElement>(root, '[data-document-list]');
    if (list) list.innerHTML = documents.length ? documents.map((item) => `<article class="document-row"><div><div class="document-row__top"><h3>${safe(item.title)}</h3><i>${safe(item.status)}</i></div><p>${safe(nameFor(item.client_id))}</p><div class="document-row__meta"><span>Version ${item.version}</span><span>${safe(item.source_filename || 'File pending')}</span><span>Updated ${new Date(item.updated_at).toLocaleDateString('en-GB')}</span></div></div>${item.storage_path ? `<div class="document-row__actions"><button class="admin-button" type="button" data-document-download="${safe(item.id)}">Download</button></div>` : ''}</article>`).join('') : '<p class="documents-empty">No client documents have been assigned yet.</p>';
    const summary = el<HTMLElement>(root, '[data-document-summary]'); if (summary) summary.textContent = `${documents.length} assigned document${documents.length === 1 ? '' : 's'}`;
  };
  const copy = async (text: string, message = 'Codex brief copied.') => { await navigator.clipboard.writeText(text); if (docStatus) docStatus.textContent = message; };
  const download = async (path: string, filename?: string | null) => { if (!db) return; const result = await db.storage.from('client-documents').createSignedUrl(path, 60); if (result.error) { if (docStatus) docStatus.textContent = result.error.message; return; } const anchor = document.createElement('a'); anchor.href = result.data.signedUrl; anchor.download = filename || ''; anchor.click(); };
  const load = async () => {
    if (!db) return; const sync = el<HTMLElement>(root, '[data-sync-status]'); if (sync) sync.textContent = 'Refreshing documents';
    const [templateResult, clientResult, documentResult] = await Promise.all([db.from('document_templates').select('*').eq('is_active', true).order('name'), db.from('clients').select('id,company_name').order('company_name'), db.from('client_documents').select('*').order('updated_at', { ascending: false })]);
    clients = (clientResult.data || []) as ClientRecord[];
    if (templateResult.error && templateResult.error.code === '42P01') templates = [fallbackTemplate]; else templates = (templateResult.data || [fallbackTemplate]) as Template[];
    documents = documentResult.error?.code === '42P01' ? [] : (documentResult.data || []) as ClientDocument[];
    render(); if (sync) sync.textContent = templateResult.error?.code === '42P01' ? 'Local preview · Documents migration pending' : `Synced ${new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
  };
  form?.addEventListener('submit', async (event) => { event.preventDefault(); if (!db) return; const values = new FormData(form); const result = await db.auth.signInWithPassword({ email: String(values.get('email') || ''), password: String(values.get('password') || '') }); if (result.error) { if (status) status.textContent = 'The email or password was not accepted.'; return; } showWorkspace(); await load(); });
  docForm?.addEventListener('submit', async (event) => { event.preventDefault(); if (!db) return; const values = new FormData(docForm); const file = values.get('file') as File; const clientId = String(values.get('client_id') || ''); if (!file?.name || !clientId || selectedTemplate().id.startsWith('local-')) { if (docStatus) docStatus.textContent = selectedTemplate().id.startsWith('local-') ? 'Run the Documents database migration before uploading.' : 'Choose a client and finished file.'; return; } const path = `clients/${clientId}/${crypto.randomUUID()}-${file.name.replace(/[^a-z0-9._-]/gi, '-')}`; const upload = await db.storage.from('client-documents').upload(path, file); if (upload.error) { if (docStatus) docStatus.textContent = upload.error.message; return; } const saved = await db.from('client_documents').insert({ template_id: selectedTemplate().id, client_id: clientId, title: String(values.get('title') || selectedTemplate().name), document_type: selectedTemplate().document_type, status: 'ready', storage_path: path, source_filename: file.name, generation_brief: { prompt: generationBrief() } }); if (saved.error) { if (docStatus) docStatus.textContent = saved.error.message; return; } docForm.reset(); if (docStatus) docStatus.textContent = 'Document uploaded and assigned.'; await load(); });
  root.addEventListener('click', async (event) => { const target = event.target as Element; const brief = target.closest<HTMLElement>('[data-template-brief]'); if (brief) { const item = templates.find(({ id }) => id === brief.dataset.templateBrief); if (item) await copy(item.codex_instructions); } const templateDownload = target.closest<HTMLElement>('[data-template-download]'); if (templateDownload) { const item = templates.find(({ id }) => id === templateDownload.dataset.templateDownload); if (item?.storage_path) await download(item.storage_path); } const documentDownload = target.closest<HTMLElement>('[data-document-download]'); if (documentDownload) { const item = documents.find(({ id }) => id === documentDownload.dataset.documentDownload); if (item?.storage_path) await download(item.storage_path, item.source_filename); } });
  el<HTMLButtonElement>(root, '[data-copy-brief]')?.addEventListener('click', () => void copy(generationBrief())); el<HTMLButtonElement>(root, '[data-refresh]')?.addEventListener('click', () => void load()); el<HTMLButtonElement>(root, '[data-sign-out]')?.addEventListener('click', async () => { await db?.auth.signOut(); showAuth(); });
  const boot = async () => { if (!url || !key) { if (status) status.textContent = 'Supabase configuration is missing.'; return; } db = createClient(url, key, { auth: { persistSession: true, autoRefreshToken: true } }); const session = await db.auth.getSession(); if (session.data.session) { showWorkspace(); await load(); } else showAuth(); }; void boot();
};
