-- Generated from the three user-supplied Brisk reports. Amounts are intentionally interpreted as GBP.
begin;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Bridge Town Interiors', 'Bridge Town Interiors', null, 'complete', null, null, 'brisk', 'bridge-town-interiors', -130000)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Browns Hair Lounge Limited', 'Browns Hair Lounge Limited', null, 'complete', '11 Lower Northam Hedge End SO30 4FN', null, 'brisk', 'browns-hair-lounge-limited', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Cheshire Design LTD', 'Cheshire Design LTD', null, 'complete', 'Gorsey Mount Street Stockport SK1 3BT', null, 'brisk', 'cheshire-design-ltd', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('D Kirkham', 'D Kirkham', null, 'complete', 'Mutual Gain Consulting Limited Unit 3, The Studios,  320 Chorley Old Road BL1 4JU', null, 'brisk', 'd-kirkham', -65000)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Hair Made Easi LTD', 'Hair Made Easi LTD', null, 'complete', 'Unit 35 & 36, Eton Business Park, Bury, Radcliffe, Manchester M26 2ZS', null, 'brisk', 'hair-made-easi-ltd', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Hear Better Limited', 'Hear Better Limited', null, 'complete', '135 Hotspur St, Newcastle upon Tyne NE6 5BH', null, 'brisk', 'hear-better-limited', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Libertybelle UK', 'Libertybelle UK', null, 'complete', '36–38 Sackville St Manchester M1 3WA', null, 'brisk', 'libertybelle-uk', 169000)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('P&A Furniture Sales Ltd', 'P&A Furniture Sales Ltd', null, 'complete', null, null, 'brisk', 'p-a-furniture-sales-ltd', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Sonnys Canaries SL', 'Sonnys Canaries SL', null, 'complete', 'B05282074 Avenida Estados Unidos 37 Playa Del Ingles 35100 Las Palmas De GC', null, 'brisk', 'sonnys-canaries-sl', 0)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Wigs By Frankie', 'Wigs By Frankie', null, 'complete', null, null, 'brisk', 'wigs-by-frankie', -36500)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.clients (company_name, primary_contact_name, primary_contact_email, status, billing_address, phone, legacy_source, legacy_key, imported_balance_pence)
values ('Ya Omri Swimwear FZE', 'Ya Omri Swimwear FZE', null, 'complete', 'Al Shmookh Business Center, One UAQ, UAQ Free Trade Zone, Umm Al Quwain', null, 'brisk', 'ya-omri-swimwear-fze', -110000)
on conflict (legacy_source, legacy_key) where legacy_source is not null and legacy_key is not null do update set company_name = excluded.company_name, billing_address = excluded.billing_address, phone = excluded.phone, imported_balance_pence = excluded.imported_balance_pence;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10435', 'brisk', '2025-04-30|10435|P&A Furniture Sales Ltd|1', '2025-04-30'::date, 'paid', 350000, 0, 350000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-04-30","Invoice":"10435","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$3,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10436', 'brisk', '2025-05-16|10436|Libertybelle UK|2', '2025-05-16'::date, 'paid', 76500, 0, 76500, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-05-16","Invoice":"10436","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$765.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10437', 'brisk', '2025-05-16|10437|Libertybelle UK|3', '2025-05-16'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-05-16","Invoice":"10437","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10438', 'brisk', '2025-06-01|10438|P&A Furniture Sales Ltd|4', '2025-06-01'::date, 'paid', 350000, 0, 350000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-06-01","Invoice":"10438","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$3,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10439', 'brisk', '2025-06-16|10439|Libertybelle UK|5', '2025-06-16'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-06-16","Invoice":"10439","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10440', 'brisk', '2025-07-01|10440|P&A Furniture Sales Ltd|6', '2025-07-01'::date, 'paid', 400000, 0, 400000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-07-01","Invoice":"10440","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$4,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10442', 'brisk', '2025-07-16|10442|P&A Furniture Sales Ltd|7', '2025-07-16'::date, 'paid', 400000, 0, 400000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-07-16","Invoice":"10442","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$4,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10441', 'brisk', '2025-07-25|10441|Libertybelle UK|8', '2025-07-25'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-07-25","Invoice":"10441","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10443', 'brisk', '2025-07-31|10443|P&A Furniture Sales Ltd|9', '2025-07-31'::date, 'paid', 250000, 0, 250000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-07-31","Invoice":"10443","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10445', 'brisk', '2025-08-20|10445|Libertybelle UK|10', '2025-08-20'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-08-20","Invoice":"10445","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10446', 'brisk', '2025-08-21|10446|Sonnys Canaries SL|11', '2025-08-21'::date, 'paid', 50000, 0, 50000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-08-21","Invoice":"10446","Customer":"Sonnys Canaries SL","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'sonnys-canaries-sl'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10447', 'brisk', '2025-08-29|10447|P&A Furniture Sales Ltd|12', '2025-08-29'::date, 'paid', 275000, 0, 275000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-08-29","Invoice":"10447","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10448', 'brisk', '2025-09-12|10448|Bridge Town Interiors|13', '2025-09-12'::date, 'paid', 95000, 0, 95000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-09-12","Invoice":"10448","Customer":"Bridge Town Interiors","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$950.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'bridge-town-interiors'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10449', 'brisk', '2025-09-23|10449|Libertybelle UK|14', '2025-09-23'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-09-23","Invoice":"10449","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10450', 'brisk', '2025-09-25|10450|Ya Omri Swimwear FZE|15', '2025-09-25'::date, 'paid', 80000, 0, 80000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-09-25","Invoice":"10450","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10451', 'brisk', '2025-09-29|10451|P&A Furniture Sales Ltd|16', '2025-09-29'::date, 'paid', 275000, 0, 275000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-09-29","Invoice":"10451","Customer":"P&A Furniture Sales Ltd","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10452', 'brisk', '2025-10-06|10452|Ya Omri Swimwear FZE|17', '2025-10-06'::date, 'paid', 110000, 0, 110000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-10-06","Invoice":"10452","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10453', 'brisk', '2025-10-28|10453|Libertybelle UK|18', '2025-10-28'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-10-28","Invoice":"10453","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10454', 'brisk', '2025-11-05|10454|Cheshire Design LTD|19', '2025-11-05'::date, 'paid', 45900, 0, 45900, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-11-05","Invoice":"10454","Customer":"Cheshire Design LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$459.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'cheshire-design-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10455', 'brisk', '2025-11-06|10455|Ya Omri Swimwear FZE|20', '2025-11-06'::date, 'paid', 160000, 0, 160000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-11-06","Invoice":"10455","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,600.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10457', 'brisk', '2025-11-24|10457|Libertybelle UK|21', '2025-11-24'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-11-24","Invoice":"10457","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10456', 'brisk', '2025-11-24|10456|Hair Made Easi LTD|22', '2025-11-24'::date, 'paid', 105000, 0, 105000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-11-24","Invoice":"10456","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,050.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10460', 'brisk', '2025-12-05|10460|Hair Made Easi LTD|23', '2025-12-05'::date, 'paid', 120000, 0, 120000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-12-05","Invoice":"10460","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10459', 'brisk', '2025-12-06|10459|Ya Omri Swimwear FZE|24', '2025-12-06'::date, 'paid', 110000, 0, 110000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-12-06","Invoice":"10459","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10465', 'brisk', '2025-12-19|10465|Hair Made Easi LTD|25', '2025-12-19'::date, 'paid', 120000, 0, 120000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-12-19","Invoice":"10465","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10461', 'brisk', '2025-12-22|10461|Libertybelle UK|26', '2025-12-22'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2025-12-22","Invoice":"10461","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10468', 'brisk', '2026-01-02|10468|Hair Made Easi LTD|27', '2026-01-02'::date, 'paid', 120000, 0, 120000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-02","Invoice":"10468","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10464', 'brisk', '2026-01-03|10464|Libertybelle UK|28', '2026-01-03'::date, 'paid', 40000, 0, 40000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-03","Invoice":"10464","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$400.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10462', 'brisk', '2026-01-03|10462|Hear Better Now LTD|29', '2026-01-03'::date, 'paid', 100000, 0, 100000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-03","Invoice":"10462","Customer":"Hear Better Now LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10489', 'brisk', '2026-01-06|10489|Ya Omri Swimwear FZE|30', '2026-01-06'::date, 'paid', 110000, 0, 110000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-06","Invoice":"10489","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10466', 'brisk', '2026-01-16|10466|Hair Made Easi LTD|31', '2026-01-16'::date, 'paid', 135000, 0, 135000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-16","Invoice":"10466","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,350.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10470', 'brisk', '2026-01-22|10470|Libertybelle UK|32', '2026-01-22'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-22","Invoice":"10470","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10471', 'brisk', '2026-01-30|10471|Hair Made Easi LTD|33', '2026-01-30'::date, 'paid', 120000, 0, 120000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-01-30","Invoice":"10471","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10474', 'brisk', '2026-02-06|10474|Ya Omri Swimwear FZE|34', '2026-02-06'::date, 'paid', 110000, 0, 110000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-06","Invoice":"10474","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10475', 'brisk', '2026-02-06|10475|Hear Better Limited|35', '2026-02-06'::date, 'paid', 55000, 0, 55000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-06","Invoice":"10475","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10476', 'brisk', '2026-02-13|10476|Hair Made Easi LTD|36', '2026-02-13'::date, 'paid', 120000, 0, 120000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-13","Invoice":"10476","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10475', 'brisk', '2026-02-13|10475|Hear Better Now LTD|37', '2026-02-13'::date, 'paid', 55000, 0, 55000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-13","Invoice":"10475","Customer":"Hear Better Now LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10463', 'brisk', '2026-02-20|10463|Libertybelle UK|38', '2026-02-20'::date, 'paid', 180000, 0, 180000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-20","Invoice":"10463","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10481', 'brisk', '2026-02-24|10481|Hair Made Easi LTD|39', '2026-02-24'::date, 'paid', 80000, 0, 80000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-02-24","Invoice":"10481","Customer":"Hair Made Easi LTD","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10482', 'brisk', '2026-03-06|10482|Ya Omri Swimwear FZE|40', '2026-03-06'::date, 'paid', 90000, 0, 90000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-03-06","Invoice":"10482","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10476', 'brisk', '2026-03-06|10476|Hear Better Limited|41', '2026-03-06'::date, 'paid', 55000, 0, 55000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-03-06","Invoice":"10476","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10488', 'brisk', '2026-03-22|10488|Libertybelle UK|42', '2026-03-22'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-03-22","Invoice":"10488","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10485', 'brisk', '2026-04-06|10485|Ya Omri Swimwear FZE|43', '2026-04-06'::date, 'paid', 90000, 0, 90000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-04-06","Invoice":"10485","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10483', 'brisk', '2026-04-06|10483|Hear Better Limited|44', '2026-04-06'::date, 'paid', 75000, 0, 75000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-04-06","Invoice":"10483","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10458', 'brisk', '2026-04-21|10458|Libertybelle UK|45', '2026-04-21'::date, 'paid', 80000, 0, 80000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-04-21","Invoice":"10458","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10469', 'brisk', '2026-04-25|10469|Libertybelle UK|46', '2026-04-25'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-04-25","Invoice":"10469","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10494', 'brisk', '2026-05-06|10494|Hear Better Limited|47', '2026-05-06'::date, 'paid', 100000, 0, 100000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-05-06","Invoice":"10494","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10491', 'brisk', '2026-05-06|10491|Ya Omri Swimwear FZE|48', '2026-05-06'::date, 'paid', 99000, 0, 99000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-05-06","Invoice":"10491","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$990.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10500', 'brisk', '2026-05-22|10500|Libertybelle UK|49', '2026-05-22'::date, 'paid', 250000, 0, 250000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-05-22","Invoice":"10500","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10499', 'brisk', '2026-05-22|10499|Libertybelle UK|50', '2026-05-22'::date, 'paid', 81000, 0, 81000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-05-22","Invoice":"10499","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10509', 'brisk', '2026-06-06|10509|Hear Better Limited|51', '2026-06-06'::date, 'paid', 110000, 0, 110000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-06-06","Invoice":"10509","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10502', 'brisk', '2026-06-06|10502|Ya Omri Swimwear FZE|52', '2026-06-06'::date, 'paid', 103000, 0, 103000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-06-06","Invoice":"10502","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$1,030.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10940', 'brisk', '2026-06-22|10940|Libertybelle UK|53', '2026-06-22'::date, 'paid', 250000, 0, 250000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-06-22","Invoice":"10940","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '10949', 'brisk', '2026-06-22|10949|Libertybelle UK|54', '2026-06-22'::date, 'paid', 250000, 0, 250000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-06-22","Invoice":"10949","Customer":"Libertybelle UK","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '102092', 'brisk', '2026-06-29|102092|Libertybelle UK|55', '2026-06-29'::date, 'overdue', 250000, 0, 250000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-06-29","Invoice":"102092","Customer":"Libertybelle UK","Salesperson":"","Status":"Overdue","Tax":"$0.00","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '1020930', 'brisk', '2026-07-06|1020930|Ya Omri Swimwear FZE|56', '2026-07-06'::date, 'paid', 90000, 0, 90000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-07-06","Invoice":"1020930","Customer":"Ya Omri Swimwear FZE","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_invoices (client_id, display_number, source, source_key, issue_date, status, subtotal_pence, tax_pence, total_pence, currency, description, source_data)
select id, '102098', 'brisk', '2026-07-06|102098|Hear Better Limited|57', '2026-07-06'::date, 'paid', 90000, 0, 90000, 'GBP', 'Imported Brisk invoice', '{"Date":"2026-07-06","Invoice":"102098","Customer":"Hear Better Limited","Salesperson":"","Status":"Paid","Tax":"$0.00","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set status = excluded.status, subtotal_pence = excluded.subtotal_pence, tax_pence = excluded.tax_pence, total_pence = excluded.total_pence, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-04-30|P&A Furniture Sales Ltd|10434|$3,500.00|1', '2025-04-30'::date, 350000, 'Cash', '10434', 'GBP', '{"Date":"2025-04-30","Customer":"P&A Furniture Sales Ltd","Invoice":"10434","Method":"Cash","Amount":"$3,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-05-16|P&A Furniture Sales Ltd|10435|$3,500.00|2', '2025-05-16'::date, 350000, 'Cash', '10435', 'GBP', '{"Date":"2025-05-16","Customer":"P&A Furniture Sales Ltd","Invoice":"10435","Method":"Cash","Amount":"$3,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-06-01|Libertybelle UK|10437|$810.00|3', '2025-06-01'::date, 81000, 'Cash', '10437', 'GBP', '{"Date":"2025-06-01","Customer":"Libertybelle UK","Invoice":"10437","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-06-01|Libertybelle UK|10436|$765.00|4', '2025-06-01'::date, 76500, 'Cash', '10436', 'GBP', '{"Date":"2025-06-01","Customer":"Libertybelle UK","Invoice":"10436","Method":"Cash","Amount":"$765.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-06-16|P&A Furniture Sales Ltd|10438|$3,500.00|5', '2025-06-16'::date, 350000, 'Cash', '10438', 'GBP', '{"Date":"2025-06-16","Customer":"P&A Furniture Sales Ltd","Invoice":"10438","Method":"Cash","Amount":"$3,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-07-01|Libertybelle UK|10439|$810.00|6', '2025-07-01'::date, 81000, 'Cash', '10439', 'GBP', '{"Date":"2025-07-01","Customer":"Libertybelle UK","Invoice":"10439","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-07-25|P&A Furniture Sales Ltd|10440|$4,000.00|7', '2025-07-25'::date, 400000, 'Cash', '10440', 'GBP', '{"Date":"2025-07-25","Customer":"P&A Furniture Sales Ltd","Invoice":"10440","Method":"Cash","Amount":"$4,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-07-25|P&A Furniture Sales Ltd|10442|$4,000.00|8', '2025-07-25'::date, 400000, 'Cash', '10442', 'GBP', '{"Date":"2025-07-25","Customer":"P&A Furniture Sales Ltd","Invoice":"10442","Method":"Cash","Amount":"$4,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-08-05|P&A Furniture Sales Ltd|10443|$2,500.00|9', '2025-08-05'::date, 250000, 'Cash', '10443', 'GBP', '{"Date":"2025-08-05","Customer":"P&A Furniture Sales Ltd","Invoice":"10443","Method":"Cash","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-08-05|Libertybelle UK|10441|$810.00|10', '2025-08-05'::date, 81000, 'Cash', '10441', 'GBP', '{"Date":"2025-08-05","Customer":"Libertybelle UK","Invoice":"10441","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-09-09|Libertybelle UK|10445|$810.00|11', '2025-09-09'::date, 81000, 'Cash', '10445', 'GBP', '{"Date":"2025-09-09","Customer":"Libertybelle UK","Invoice":"10445","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-09-09|Sonnys Canaries SL|10446|$500.00|12', '2025-09-09'::date, 50000, 'Cash', '10446', 'GBP', '{"Date":"2025-09-09","Customer":"Sonnys Canaries SL","Invoice":"10446","Method":"Cash","Amount":"$500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'sonnys-canaries-sl'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-09-09|P&A Furniture Sales Ltd|10447|$2,750.00|13', '2025-09-09'::date, 275000, 'Cash', '10447', 'GBP', '{"Date":"2025-09-09","Customer":"P&A Furniture Sales Ltd","Invoice":"10447","Method":"Cash","Amount":"$2,750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-09-18|Bridge Town Interiors|10448|$950.00|14', '2025-09-18'::date, 95000, 'Cash', '10448', 'GBP', '{"Date":"2025-09-18","Customer":"Bridge Town Interiors","Invoice":"10448","Method":"Cash","Amount":"$950.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'bridge-town-interiors'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-09-29|Ya Omri Swimwear FZE|10450|$800.00|15', '2025-09-29'::date, 80000, 'Cash', '10450', 'GBP', '{"Date":"2025-09-29","Customer":"Ya Omri Swimwear FZE","Invoice":"10450","Method":"Cash","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-10-01|P&A Furniture Sales Ltd|10451|$2,750.00|16', '2025-10-01'::date, 275000, 'Cash', '10451', 'GBP', '{"Date":"2025-10-01","Customer":"P&A Furniture Sales Ltd","Invoice":"10451","Method":"Cash","Amount":"$2,750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'p-a-furniture-sales-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-10-06|Libertybelle UK|10449|$810.00|17', '2025-10-06'::date, 81000, 'Cash', '10449', 'GBP', '{"Date":"2025-10-06","Customer":"Libertybelle UK","Invoice":"10449","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-10-14|Ya Omri Swimwear FZE|10452|$1,100.00|18', '2025-10-14'::date, 110000, 'Cash', '10452', 'GBP', '{"Date":"2025-10-14","Customer":"Ya Omri Swimwear FZE","Invoice":"10452","Method":"Cash","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-11-24|Ya Omri Swimwear FZE|10455|$1,600.00|19', '2025-11-24'::date, 160000, 'Cash', '10455', 'GBP', '{"Date":"2025-11-24","Customer":"Ya Omri Swimwear FZE","Invoice":"10455","Method":"Cash","Amount":"$1,600.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-11-24|Cheshire Design LTD|10454|$459.00|20', '2025-11-24'::date, 45900, 'Cash', '10454', 'GBP', '{"Date":"2025-11-24","Customer":"Cheshire Design LTD","Invoice":"10454","Method":"Cash","Amount":"$459.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'cheshire-design-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-11-24|Libertybelle UK|10453|$810.00|21', '2025-11-24'::date, 81000, 'Cash', '10453', 'GBP', '{"Date":"2025-11-24","Customer":"Libertybelle UK","Invoice":"10453","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-12-05|Libertybelle UK|10457|$810.00|22', '2025-12-05'::date, 81000, 'Cash', '10457', 'GBP', '{"Date":"2025-12-05","Customer":"Libertybelle UK","Invoice":"10457","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-12-05|Hair Made Easi LTD|10456|$1,050.00|23', '2025-12-05'::date, 105000, 'Cash', '10456', 'GBP', '{"Date":"2025-12-05","Customer":"Hair Made Easi LTD","Invoice":"10456","Method":"Cash","Amount":"$1,050.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-12-17|Ya Omri Swimwear FZE|10459|$1,100.00|24', '2025-12-17'::date, 110000, 'Cash', '10459', 'GBP', '{"Date":"2025-12-17","Customer":"Ya Omri Swimwear FZE","Invoice":"10459","Method":"Cash","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2025-12-17|Hair Made Easi LTD|10460|$1,200.00|25', '2025-12-17'::date, 120000, 'Cash', '10460', 'GBP', '{"Date":"2025-12-17","Customer":"Hair Made Easi LTD","Invoice":"10460","Method":"Cash","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Libertybelle UK|10461, 10461|$1,620.00|26', '2026-01-03'::date, 162000, 'Cash', '10461, 10461', 'GBP', '{"Date":"2026-01-03","Customer":"Libertybelle UK","Invoice":"10461, 10461","Method":"Cash","Amount":"$1,620.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Hear Better Now LTD|10462|$1,000.00|27', '2026-01-03'::date, 100000, 'Cash', '10462', 'GBP', '{"Date":"2026-01-03","Customer":"Hear Better Now LTD","Invoice":"10462","Method":"Cash","Amount":"$1,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Bridge Town Interiors||$350.00|28', '2026-01-03'::date, 35000, 'Cash', null, 'GBP', '{"Date":"2026-01-03","Customer":"Bridge Town Interiors","Invoice":"","Method":"Cash","Amount":"$350.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'bridge-town-interiors'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Bridge Town Interiors||$950.00|29', '2026-01-03'::date, 95000, 'Cash', null, 'GBP', '{"Date":"2026-01-03","Customer":"Bridge Town Interiors","Invoice":"","Method":"Cash","Amount":"$950.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'bridge-town-interiors'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Bridge Town Interiors|10448|$350.00|30', '2026-01-03'::date, 35000, 'Cash', '10448', 'GBP', '{"Date":"2026-01-03","Customer":"Bridge Town Interiors","Invoice":"10448","Method":"Cash","Amount":"$350.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'bridge-town-interiors'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Libertybelle UK|10464|$400.00|31', '2026-01-03'::date, 40000, 'Cash', '10464', 'GBP', '{"Date":"2026-01-03","Customer":"Libertybelle UK","Invoice":"10464","Method":"Cash","Amount":"$400.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-03|Hair Made Easi LTD|10465|$1,200.00|32', '2026-01-03'::date, 120000, 'Cash', '10465', 'GBP', '{"Date":"2026-01-03","Customer":"Hair Made Easi LTD","Invoice":"10465","Method":"Cash","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-07|Hair Made Easi LTD|10468|$1,200.00|33', '2026-01-07'::date, 120000, 'Cash', '10468', 'GBP', '{"Date":"2026-01-07","Customer":"Hair Made Easi LTD","Invoice":"10468","Method":"Cash","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-19|Ya Omri Swimwear FZE|10489, 10489|$2,200.00|34', '2026-01-19'::date, 220000, 'Cash', '10489, 10489', 'GBP', '{"Date":"2026-01-19","Customer":"Ya Omri Swimwear FZE","Invoice":"10489, 10489","Method":"Cash","Amount":"$2,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-22|Hair Made Easi LTD|10466|$1,350.00|35', '2026-01-22'::date, 135000, 'Cash', '10466', 'GBP', '{"Date":"2026-01-22","Customer":"Hair Made Easi LTD","Invoice":"10466","Method":"Cash","Amount":"$1,350.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-01-31|Libertybelle UK|10470|$810.00|36', '2026-01-31'::date, 81000, 'Cash', '10470', 'GBP', '{"Date":"2026-01-31","Customer":"Libertybelle UK","Invoice":"10470","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-02-06|Hair Made Easi LTD|10471|$1,200.00|37', '2026-02-06'::date, 120000, 'Cash', '10471', 'GBP', '{"Date":"2026-02-06","Customer":"Hair Made Easi LTD","Invoice":"10471","Method":"Cash","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-02-13|Ya Omri Swimwear FZE|10474|$1,100.00|38', '2026-02-13'::date, 110000, 'Cash', '10474', 'GBP', '{"Date":"2026-02-13","Customer":"Ya Omri Swimwear FZE","Invoice":"10474","Method":"Cash","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-02-17|Hear Better Now LTD|10475|$550.00|39', '2026-02-17'::date, 55000, 'Cash', '10475', 'GBP', '{"Date":"2026-02-17","Customer":"Hear Better Now LTD","Invoice":"10475","Method":"Cash","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-02-17|Hair Made Easi LTD|10476|$1,200.00|40', '2026-02-17'::date, 120000, 'Cash', '10476', 'GBP', '{"Date":"2026-02-17","Customer":"Hair Made Easi LTD","Invoice":"10476","Method":"Cash","Amount":"$1,200.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-03-06|Hair Made Easi LTD|10481|$800.00|41', '2026-03-06'::date, 80000, 'Cash', '10481', 'GBP', '{"Date":"2026-03-06","Customer":"Hair Made Easi LTD","Invoice":"10481","Method":"Cash","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hair-made-easi-ltd'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-03-06|Hear Better Limited|10475|$550.00|42', '2026-03-06'::date, 55000, 'Cash', '10475', 'GBP', '{"Date":"2026-03-06","Customer":"Hear Better Limited","Invoice":"10475","Method":"Cash","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-03-24|Ya Omri Swimwear FZE|10482|$900.00|43', '2026-03-24'::date, 90000, 'Cash', '10482', 'GBP', '{"Date":"2026-03-24","Customer":"Ya Omri Swimwear FZE","Invoice":"10482","Method":"Cash","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-03-24|Hear Better Limited|10476|$550.00|44', '2026-03-24'::date, 55000, 'Cash', '10476', 'GBP', '{"Date":"2026-03-24","Customer":"Hear Better Limited","Invoice":"10476","Method":"Cash","Amount":"$550.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-04-08|Hear Better Limited|10483|$750.00|45', '2026-04-08'::date, 75000, 'Cash', '10483', 'GBP', '{"Date":"2026-04-08","Customer":"Hear Better Limited","Invoice":"10483","Method":"Cash","Amount":"$750.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-04-08|Ya Omri Swimwear FZE|10485|$900.00|46', '2026-04-08'::date, 90000, 'Cash', '10485', 'GBP', '{"Date":"2026-04-08","Customer":"Ya Omri Swimwear FZE","Invoice":"10485","Method":"Cash","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-04-17|Libertybelle UK|10488|$810.00|47', '2026-04-17'::date, 81000, 'Cash', '10488', 'GBP', '{"Date":"2026-04-17","Customer":"Libertybelle UK","Invoice":"10488","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-04-17|Libertybelle UK|10463|$1,800.00|48', '2026-04-17'::date, 180000, 'Cash', '10463', 'GBP', '{"Date":"2026-04-17","Customer":"Libertybelle UK","Invoice":"10463","Method":"Cash","Amount":"$1,800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-05-06|Libertybelle UK|10458|$800.00|49', '2026-05-06'::date, 80000, 'Cash', '10458', 'GBP', '{"Date":"2026-05-06","Customer":"Libertybelle UK","Invoice":"10458","Method":"Cash","Amount":"$800.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-05-07|Libertybelle UK|10469|$810.00|50', '2026-05-07'::date, 81000, 'Cash', '10469', 'GBP', '{"Date":"2026-05-07","Customer":"Libertybelle UK","Invoice":"10469","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-05-07|Ya Omri Swimwear FZE|10491|$990.00|51', '2026-05-07'::date, 99000, 'Cash', '10491', 'GBP', '{"Date":"2026-05-07","Customer":"Ya Omri Swimwear FZE","Invoice":"10491","Method":"Cash","Amount":"$990.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-05-22|Hear Better Limited|10494|$1,000.00|52', '2026-05-22'::date, 100000, 'Cash', '10494', 'GBP', '{"Date":"2026-05-22","Customer":"Hear Better Limited","Invoice":"10494","Method":"Cash","Amount":"$1,000.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-06-07|Libertybelle UK|10500|$2,500.00|53', '2026-06-07'::date, 250000, 'Cash', '10500', 'GBP', '{"Date":"2026-06-07","Customer":"Libertybelle UK","Invoice":"10500","Method":"Cash","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-06-07|Libertybelle UK|10499|$810.00|54', '2026-06-07'::date, 81000, 'Cash', '10499', 'GBP', '{"Date":"2026-06-07","Customer":"Libertybelle UK","Invoice":"10499","Method":"Cash","Amount":"$810.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-06-07|Hear Better Limited|10509|$1,100.00|55', '2026-06-07'::date, 110000, 'Cash', '10509', 'GBP', '{"Date":"2026-06-07","Customer":"Hear Better Limited","Invoice":"10509","Method":"Cash","Amount":"$1,100.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-06-22|Ya Omri Swimwear FZE|10502|$1,030.00|56', '2026-06-22'::date, 103000, 'Cash', '10502', 'GBP', '{"Date":"2026-06-22","Customer":"Ya Omri Swimwear FZE","Invoice":"10502","Method":"Cash","Amount":"$1,030.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-06-29|Libertybelle UK|10940|$2,500.00|57', '2026-06-29'::date, 250000, 'Cash', '10940', 'GBP', '{"Date":"2026-06-29","Customer":"Libertybelle UK","Invoice":"10940","Method":"Cash","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-07-06|Libertybelle UK|10949|$2,500.00|58', '2026-07-06'::date, 250000, 'Cash', '10949', 'GBP', '{"Date":"2026-07-06","Customer":"Libertybelle UK","Invoice":"10949","Method":"Cash","Amount":"$2,500.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'libertybelle-uk'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-07-20|Hear Better Limited|102098|$900.00|59', '2026-07-20'::date, 90000, 'Cash', '102098', 'GBP', '{"Date":"2026-07-20","Customer":"Hear Better Limited","Invoice":"102098","Method":"Cash","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'hear-better-limited'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
insert into public.finance_payments (client_id, source, source_key, payment_date, amount_pence, method, reference, currency, source_data)
select id, 'brisk', '2026-07-20|Ya Omri Swimwear FZE|1020930|$900.00|60', '2026-07-20'::date, 90000, 'Cash', '1020930', 'GBP', '{"Date":"2026-07-20","Customer":"Ya Omri Swimwear FZE","Invoice":"1020930","Method":"Cash","Amount":"$900.00"}'::jsonb from public.clients where legacy_source = 'brisk' and legacy_key = 'ya-omri-swimwear-fze'
on conflict (source, source_key) do update set amount_pence = excluded.amount_pence, method = excluded.method, reference = excluded.reference, source_data = excluded.source_data;
commit;
